# This file allows you to configure your python environment quickly for prednet.
# Please refer to the conda documentation for more info:
# https://conda.io/docs/user-guide/tasks/manage-environments.html

name: prednet

dependencies:
  - python=3.6

  - pip:
    - keras==2.2.4
    - tensorflow-gpu==1.12.0
    - hickle==3.3.0
    - matplotlib
    - imageio==2.4.0
    - scikit-learn==0.20.1